### ISSUE TITLE
Error in 08-Implementation/Neural%20Network%20Advection.ipynb

### ISSUE THREAD

**Issue by rabernat** [m2lines/L96_demo#29]
When I try to execute this notebook I get the following error in cell 43

```python
# This might work well for F=20

gcm_nn4_x10 = GCM_network_S(Forcing_x10, nn_3l_loss4)
xnn4_x10, tnn4_x10 = gcm_nn4_x10(init_cond, dt, int(T / dt), nn_3l_loss4)


CompExps(
    [t2d_x10, x2d_x10, "2d"],
    [
        [tnn4_x10, xnn4_x10, "1d w/ rescaled NN mom."],
    ],
)
```

<details>
<summary>traceback</summary>

```
/var/folders/n8/63q49ms55wxcj_gfbtykwp5r0000gn/T/ipykernel_24547/2792372065.py:25: RuntimeWarning: overflow encountered in square
  a.plot(TN, np.sum(XN**2, axis=1), label=LN, linewidth=2)
/opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/var/folders/n8/63q49ms55wxcj_gfbtykwp5r0000gn/T/ipykernel_24547/2792372065.py:31: RuntimeWarning: overflow encountered in square
  _Y.append(np.percentile(np.sum(XN[int(5 // dt) :] ** 2, axis=1), ii))
/opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/numpy/lib/function_base.py:4009: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
/opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/transforms.py:396: RuntimeWarning: overflow encountered in double_scalars
  return (x0, y0, x1 - x0, y1 - y0)
Error in callback <function install_repl_displayhook.<locals>.post_execute at 0x1101ac670> (for post_execute):
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/pyplot.py:138, in install_repl_displayhook.<locals>.post_execute()
    136 def post_execute():
    137     if matplotlib.is_interactive():
--> 138         draw_all()

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/_pylab_helpers.py:137, in Gcf.draw_all(cls, force)
    135 for manager in cls.get_all_fig_managers():
    136     if force or manager.canvas.figure.stale:
--> 137         manager.canvas.draw_idle()

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/backend_bases.py:2060, in FigureCanvasBase.draw_idle(self, *args, **kwargs)
   2058 if not self._is_idle_drawing:
   2059     with self._idle_draw_cntx():
-> 2060         self.draw(*args, **kwargs)

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py:436, in FigureCanvasAgg.draw(self)
    432 # Acquire a lock on the shared font cache.
    433 with RendererAgg.lock, \
    434      (self.toolbar._wait_cursor_for_draw_cm() if self.toolbar
    435       else nullcontext()):
--> 436     self.figure.draw(self.renderer)
    437     # A GUI class may be need to update a window using this draw, so
    438     # don't forget to call the superclass.
    439     super().draw()

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/artist.py:73, in _finalize_rasterization.<locals>.draw_wrapper(artist, renderer, *args, **kwargs)
     71 @wraps(draw)
     72 def draw_wrapper(artist, renderer, *args, **kwargs):
---> 73     result = draw(artist, renderer, *args, **kwargs)
     74     if renderer._rasterizing:
     75         renderer.stop_rasterizing()

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/artist.py:50, in allow_rasterization.<locals>.draw_wrapper(artist, renderer)
     47     if artist.get_agg_filter() is not None:
     48         renderer.start_filter()
---> 50     return draw(artist, renderer)
     51 finally:
     52     if artist.get_agg_filter() is not None:

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/figure.py:2810, in Figure.draw(self, renderer)
   2807         # ValueError can occur when resizing a window.
   2809 self.patch.draw(renderer)
-> 2810 mimage._draw_list_compositing_images(
   2811     renderer, self, artists, self.suppressComposite)
   2813 for sfig in self.subfigs:
   2814     sfig.draw(renderer)

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/image.py:132, in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130 if not_composite or not has_images:
    131     for a in artists:
--> 132         a.draw(renderer)
    133 else:
    134     # Composite any adjacent images together
    135     image_group = []

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/artist.py:50, in allow_rasterization.<locals>.draw_wrapper(artist, renderer)
     47     if artist.get_agg_filter() is not None:
     48         renderer.start_filter()
---> 50     return draw(artist, renderer)
     51 finally:
     52     if artist.get_agg_filter() is not None:

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/axes/_base.py:3082, in _AxesBase.draw(self, renderer)
   3079         a.draw(renderer)
   3080     renderer.stop_rasterizing()
-> 3082 mimage._draw_list_compositing_images(
   3083     renderer, self, artists, self.figure.suppressComposite)
   3085 renderer.close_group('axes')
   3086 self.stale = False

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/image.py:132, in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130 if not_composite or not has_images:
    131     for a in artists:
--> 132         a.draw(renderer)
    133 else:
    134     # Composite any adjacent images together
    135     image_group = []

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/artist.py:50, in allow_rasterization.<locals>.draw_wrapper(artist, renderer)
     47     if artist.get_agg_filter() is not None:
     48         renderer.start_filter()
---> 50     return draw(artist, renderer)
     51 finally:
     52     if artist.get_agg_filter() is not None:

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/axis.py:1158, in Axis.draw(self, renderer, *args, **kwargs)
   1155     return
   1156 renderer.open_group(__name__, gid=self.get_gid())
-> 1158 ticks_to_draw = self._update_ticks()
   1159 ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
   1160                                                         renderer)
   1162 for tick in ticks_to_draw:

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/axis.py:1045, in Axis._update_ticks(self)
   1040 def _update_ticks(self):
   1041     """
   1042     Update ticks (position and labels) using the current data interval of
   1043     the axes.  Return the list of ticks that will be drawn.
   1044     """
-> 1045     major_locs = self.get_majorticklocs()
   1046     major_labels = self.major.formatter.format_ticks(major_locs)
   1047     major_ticks = self.get_major_ticks(len(major_locs))

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/axis.py:1277, in Axis.get_majorticklocs(self)
   1275 def get_majorticklocs(self):
   1276     """Return this Axis' major tick locations in data coordinates."""
-> 1277     return self.major.locator()

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/ticker.py:2114, in MaxNLocator.__call__(self)
   2112 def __call__(self):
   2113     vmin, vmax = self.axis.get_view_interval()
-> 2114     return self.tick_values(vmin, vmax)

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/ticker.py:2122, in MaxNLocator.tick_values(self, vmin, vmax)
   2119     vmin = -vmax
   2120 vmin, vmax = mtransforms.nonsingular(
   2121     vmin, vmax, expander=1e-13, tiny=1e-14)
-> 2122 locs = self._raw_ticks(vmin, vmax)
   2124 prune = self._prune
   2125 if prune == 'lower':

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/ticker.py:2078, in MaxNLocator._raw_ticks(self, vmin, vmax)
   2075     igood = (steps < 1) | (np.abs(steps - np.round(steps)) < 0.001)
   2076     steps = steps[igood]
-> 2078 istep = np.nonzero(steps >= raw_step)[0][0]
   2080 # Classic round_numbers mode may require a larger step.
   2081 if mpl.rcParams['axes.autolimit_mode'] == 'round_numbers':

IndexError: index 0 is out of bounds for axis 0 with size 0
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib_inline/backend_inline.py:43, in show(close, block)
     39 try:
     40     for figure_manager in Gcf.get_all_fig_managers():
     41         display(
     42             figure_manager.canvas.figure,
---> 43             metadata=_fetch_figure_metadata(figure_manager.canvas.figure)
     44         )
     45 finally:
     46     show._to_draw = []

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib_inline/backend_inline.py:231, in _fetch_figure_metadata(fig)
    228 # determine if a background is needed for legibility
    229 if _is_transparent(fig.get_facecolor()):
    230     # the background is transparent
--> 231     ticksLight = _is_light([label.get_color()
    232                             for axes in fig.axes
    233                             for axis in (axes.xaxis, axes.yaxis)
    234                             for label in axis.get_ticklabels()])
    235     if ticksLight.size and (ticksLight == ticksLight[0]).all():
    236         # there are one or more tick labels, all with the same lightness
    237         return {'needs_background': 'dark' if ticksLight[0] else 'light'}

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib_inline/backend_inline.py:234, in <listcomp>(.0)
    228 # determine if a background is needed for legibility
    229 if _is_transparent(fig.get_facecolor()):
    230     # the background is transparent
    231     ticksLight = _is_light([label.get_color()
    232                             for axes in fig.axes
    233                             for axis in (axes.xaxis, axes.yaxis)
--> 234                             for label in axis.get_ticklabels()])
    235     if ticksLight.size and (ticksLight == ticksLight[0]).all():
    236         # there are one or more tick labels, all with the same lightness
    237         return {'needs_background': 'dark' if ticksLight[0] else 'light'}

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/axis.py:1249, in Axis.get_ticklabels(self, minor, which)
   1247 if minor:
   1248     return self.get_minorticklabels()
-> 1249 return self.get_majorticklabels()

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/axis.py:1201, in Axis.get_majorticklabels(self)
   1199 def get_majorticklabels(self):
   1200     """Return this Axis' major tick labels, as a list of `~.text.Text`."""
-> 1201     ticks = self.get_major_ticks()
   1202     labels1 = [tick.label1 for tick in ticks if tick.label1.get_visible()]
   1203     labels2 = [tick.label2 for tick in ticks if tick.label2.get_visible()]

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/axis.py:1371, in Axis.get_major_ticks(self, numticks)
   1369 r"""Return the list of major `.Tick`\s."""
   1370 if numticks is None:
-> 1371     numticks = len(self.get_majorticklocs())
   1373 while len(self.majorTicks) < numticks:
   1374     # Update the new tick label properties from the old.
   1375     tick = self._get_tick(major=True)

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/axis.py:1277, in Axis.get_majorticklocs(self)
   1275 def get_majorticklocs(self):
   1276     """Return this Axis' major tick locations in data coordinates."""
-> 1277     return self.major.locator()

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/ticker.py:2114, in MaxNLocator.__call__(self)
   2112 def __call__(self):
   2113     vmin, vmax = self.axis.get_view_interval()
-> 2114     return self.tick_values(vmin, vmax)

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/ticker.py:2122, in MaxNLocator.tick_values(self, vmin, vmax)
   2119     vmin = -vmax
   2120 vmin, vmax = mtransforms.nonsingular(
   2121     vmin, vmax, expander=1e-13, tiny=1e-14)
-> 2122 locs = self._raw_ticks(vmin, vmax)
   2124 prune = self._prune
   2125 if prune == 'lower':

File /opt/miniconda3/envs/L96M2lines/lib/python3.9/site-packages/matplotlib/ticker.py:2078, in MaxNLocator._raw_ticks(self, vmin, vmax)
   2075     igood = (steps < 1) | (np.abs(steps - np.round(steps)) < 0.001)
   2076     steps = steps[igood]
-> 2078 istep = np.nonzero(steps >= raw_step)[0][0]
   2080 # Classic round_numbers mode may require a larger step.
   2081 if mpl.rcParams['axes.autolimit_mode'] == 'round_numbers':

IndexError: index 0 is out of bounds for axis 0 with size 0

```
</details>

**Comment by breichl** [comment]
Thanks @rabernat I'll double check why this is happening and see if I had a workaround I forgot to include here.

**Comment by breichl** [comment]
I'm unable to reproduce this error with my python environment.  I've asked @aakashsane to have a look and see if he can reproduce it.

**Comment by aakashsane** [comment]
I got the exact error as @rabernat got above. 
This is the error I got after executing cell 43

`# This might work well for F=20

gcm_nn4_x10 = GCM_network_S(Forcing_x10, nn_3l_loss4)
xnn4_x10, tnn4_x10 = gcm_nn4_x10(init_cond, dt, int(T / dt), nn_3l_loss4)


CompExps(
    [t2d_x10, x2d_x10, "2d"],
    [
        [tnn4_x10, xnn4_x10, "1d w/ rescaled NN mom."],
    ],
)`

**Comment by breichl** [comment]
Thanks @aakashsane , I think I have an idea what is probably triggering the error now.  I'll work up a patch.

**Comment by rabernat** [comment]
This is resolved in the automated build system (#33), so I think it can be closed. I don't know what the issue was, but having a standard build environment seems to fix it.

**Comment by breichl** [comment]
The error is still there, so I'm reopening and will address this cell error.
